package com.greenmark.common.config;

/**
 * @formatter:off
 * <p>Copyright: Copyright (c) 2021</p>
 * <p>Company: Greenman Financial Services, Inc.</p>
 *  
 * <p>Title: ConfigStrategy</p>
 * <p>Description: The constants in this file point to a location in the Strategy XML heirarchy (strategy.xml).
 * These configuration points are for the Strategies and Technical indicators.</p>
 *
 * @author Monte Seibel
 * @version 7.0
 * @formatter:on
 */

public class ConfigStrategy {
	private static final String CLASSNAME = "ConfigStrategy";

	public static final int NUM_EXTRA_PTS_TO_RETRIEVE = 3;

	public static final String MODEL_STOCHK_NUM_PERIODS = "DV:XML.MODEL.MKTD.SCENARIO.NUMPERIODSSTOCHK";
	public static final String MODEL_STOCHD_NUM_PERIODS = "DV:XML.MODEL.MKTD.SCENARIO.NUMPERIODSSTOCHD";

	public static final String MODEL_MACD_NUM_PERIODS_LONG = "DV:XML.MODEL.MKTD.SCENARIO.NUMPERIODSMACD.LONG";
	public static final String MODEL_MACD_NUM_PERIODS_SHORT = "DV:XML.MODEL.MKTD.SCENARIO.NUMPERIODSMACD.SHORT";
	public static final String MODEL_MACD_NUM_PERIODS_SLOW = "DV:XML.MODEL.MKTD.SCENARIO.NUMPERIODSMACD.SLOW";

	// EXCHANGE PARAMETERS
	public static final String MODEL_USE_STOCK_EXCHANGES = "DV:XML.MODEL.APPLICATION.STOCK_EXCHANGES";
	public static final String MODEL_USE_24_HOUR_EXCHANGES = "DV:XML.MODEL.APPLICATION.24_HOUR_EXCHANGES";
	public static final String MODEL_USE_FOREX = "DV:XML.MODEL.APPLICATION.USE_FOREX";
	public static final String MODEL_USE_CRYTPO = "DV:XML.MODEL.APPLICATION.USE_CRYPTO";

	// STRATEGY PARAMETERS
	public static final String MODEL_USE_INTERPERIOD_DATA = "DV:XML.MODEL.APPLICATION.USE_INTERPERIOD_DATA";

	public static final String MODEL_DISABLE_ADD_REJECTED_POPUPS = "DV:XML.MODEL.APPLICATION.DISABLE_ADD_REJECTED_POPUPS";

	// This config point will toggle whether the first harvester query uses IQChart Scan or our History DB.
	public static final String MODEL_LONG_OR_SHORT_STRATEGY = "DV:XML.MODEL.APPLICATION.LONG_OR_SHORT_STRATEGY";

	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// ----------------------------------------------- BUY LONG StrategyDto Configuration Parameters --------------------------------------------------
	// ---------------------------------------------------------------------------------------------------------------------------------------------

	// BUY LONG Parameters - DAILY
	public static final String MODEL_BUY_LONG_DAILY_MAX_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MAXPERIODSINBUCKET";

	public static final String MODEL_BUY_LONG_DAILY_LOWPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.GAUGE";
	public static final String MODEL_BUY_LONG_DAILY_LOWPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.NUMPERIODSFORLOWPT";

	public static final String MODEL_BUY_LONG_DAILY_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.USE_MOMENTUM";
	public static final String MODEL_BUY_LONG_DAILY_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MOMENTUM_TYPE";
	public static final String MODEL_BUY_LONG_DAILY_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_LONG_DAILY_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.SLOPE.USE";
	public static final String MODEL_BUY_LONG_DAILY_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_LONG_DAILY_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MACD.USE";
	public static final String MODEL_BUY_LONG_DAILY_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MACD.THRESHOLD";

	public static final String MODEL_BUY_LONG_DAILY_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MACD.USE_PERIODS";
	public static final String MODEL_BUY_LONG_DAILY_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_LONG_DAILY_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_LONG_DAILY_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.EXIT_TIMEFRAME";

	public static final String MODEL_BUY_LONG_DAILY_834_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.USE";
	public static final String MODEL_BUY_LONG_DAILY_834_FILTER_SPIKES = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.FILTER_SPIKES";
	public static final String MODEL_BUY_LONG_DAILY_834_EMA8_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.EMA8_PERIODS";
	public static final String MODEL_BUY_LONG_DAILY_834_SMA14_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.SMA14_PERIODS";
	public static final String MODEL_BUY_LONG_DAILY_834_SMA20_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.SMA20_PERIODS";
	public static final String MODEL_BUY_LONG_DAILY_834_EMA34_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.EMA34_PERIODS";

	public static final String MODEL_BUY_LONG_DAILY_834_SMA20_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.SMA20_STOPLOSS_PERIODS";
	public static final String MODEL_BUY_LONG_DAILY_834_EMA34_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.EMA34_STOPLOSS_PERIODS";

	public static final String MODEL_BUY_LONG_DAILY_834_WAIT_PERIODS_SINCE_SOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.WAIT_PERIODS_SINCE_SOLD";
	public static final String MODEL_BUY_LONG_DAILY_834_WAIT_PERIODS_CONFIRM34 = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.WAIT_PERIODS_CONFIRM34";
	public static final String MODEL_BUY_LONG_DAILY_834_CONFIRM_PRICE_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.CONFIRM_PRICE_PERCENT";

	public static final String MODEL_BUY_LONG_DAILY_834_ONENTRY_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.ONENTRY_ORDER_PERCENT";
	public static final String MODEL_BUY_LONG_DAILY_834_ONCONFIRM_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.DAILY.STRATEGY_834.ONCONFIRM_ORDER_PERCENT";

	// BUY LONG Parameters - MIN60
	public static final String MODEL_BUY_LONG_MINUTE60_MAX_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MAXPERIODSINBUCKET";

	public static final String MODEL_BUY_LONG_MINUTE60_LOWPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.NUMPERIODSFORLOWPT";
	public static final String MODEL_BUY_LONG_MINUTE60_LOWPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.GAUGE";

	public static final String MODEL_BUY_LONG_MINUTE60_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.USE_MOMENTUM";
	public static final String MODEL_BUY_LONG_MINUTE60_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MOMENTUM_TYPE";
	public static final String MODEL_BUY_LONG_MINUTE60_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_LONG_MINUTE60_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.SLOPE.USE";
	public static final String MODEL_BUY_LONG_MINUTE60_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_LONG_MINUTE60_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MACD.USE";
	public static final String MODEL_BUY_LONG_MINUTE60_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MACD.THRESHOLD";
	public static final String MODEL_BUY_LONG_MINUTE60_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MACD.USE_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE60_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_LONG_MINUTE60_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_LONG_MINUTE60_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.EXIT_TIMEFRAME";

	public static final String MODEL_BUY_LONG_MINUTE60_834_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.USE";
	public static final String MODEL_BUY_LONG_MINUTE60_834_FILTER_SPIKES = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.FILTER_SPIKES";
	public static final String MODEL_BUY_LONG_MINUTE60_834_EMA8_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.EMA8_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE60_834_SMA14_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.SMA14_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE60_834_SMA20_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.SMA20_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE60_834_EMA34_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.EMA34_PERIODS";

	public static final String MODEL_BUY_LONG_MINUTE60_834_SMA20_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.SMA20_STOPLOSS_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE60_834_EMA34_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.EMA34_STOPLOSS_PERIODS";

	public static final String MODEL_BUY_LONG_MINUTE60_834_WAIT_PERIODS_SINCE_SOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.WAIT_PERIODS_SINCE_SOLD";
	public static final String MODEL_BUY_LONG_MINUTE60_834_WAIT_PERIODS_CONFIRM34 = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.WAIT_PERIODS_CONFIRM34";
	public static final String MODEL_BUY_LONG_MINUTE60_834_CONFIRM_PRICE_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.CONFIRM_PRICE_PERCENT";

	public static final String MODEL_BUY_LONG_MINUTE60_834_ONENTRY_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.ONENTRY_ORDER_PERCENT";
	public static final String MODEL_BUY_LONG_MINUTE60_834_ONCONFIRM_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN60.STRATEGY_834.ONCONFIRM_ORDER_PERCENT";

	// BUY LONG Parameters - MIN15
	public static final String MODEL_BUY_LONG_MINUTE15_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.USE_MOMENTUM";
	public static final String MODEL_BUY_LONG_MINUTE15_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.MOMENTUM_TYPE";
	public static final String MODEL_BUY_LONG_MINUTE15_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.MOMENTUM_THRESHOLD";
	public static final String MODEL_BUY_LONG_MINUTE15_MOMENTUM_EXIT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.EXIT_MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_LONG_MINUTE15_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.SLOPE.USE";
	public static final String MODEL_BUY_LONG_MINUTE15_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_LONG_MINUTE15_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.MACD.USE";
	public static final String MODEL_BUY_LONG_MINUTE15_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.MACD.THRESHOLD";
	public static final String MODEL_BUY_LONG_MINUTE15_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.MACD.USE_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE15_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_LONG_MINUTE15_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_LONG_MINUTE15_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN15.EXIT_TIMEFRAME";

	// BUY LONG Parameters - MIN05
	public static final String MODEL_BUY_LONG_MINUTE05_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.USE_MOMENTUM";
	public static final String MODEL_BUY_LONG_MINUTE05_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.MOMENTUM_TYPE";
	public static final String MODEL_BUY_LONG_MINUTE05_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.MOMENTUM_THRESHOLD";
	public static final String MODEL_BUY_LONG_MINUTE05_MOMENTUM_EXIT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.EXIT_MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_LONG_MINUTE05_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.PRICELAGPERIODS";
	public static final String MODEL_BUY_LONG_USE_MINUTE01 = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.USE_MIN01";

	public static final String MODEL_BUY_LONG_MINUTE05_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.SLOPE.USE";
	public static final String MODEL_BUY_LONG_MINUTE05_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_LONG_MINUTE05_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.MACD.USE";
	public static final String MODEL_BUY_LONG_MINUTE05_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.MACD.THRESHOLD";
	public static final String MODEL_BUY_LONG_MINUTE05_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.MACD.USE_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE05_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_LONG_MINUTE05_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN05.MACD.USE_SIGNAL";

	// BUY LONG Parameters - MIN01
	public static final String MODEL_BUY_LONG_MINUTE01_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.USE_MOMENTUM";
	public static final String MODEL_BUY_LONG_MINUTE01_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.MOMENTUM_TYPE";
	public static final String MODEL_BUY_LONG_MINUTE01_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.MOMENTUM_THRESHOLD";
	public static final String MODEL_BUY_LONG_MINUTE01_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.PRICELAGPERIODS";

	public static final String MODEL_BUY_LONG_MINUTE01_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.SLOPE.USE";
	public static final String MODEL_BUY_LONG_MINUTE01_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_LONG_MINUTE01_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.MACD.USE";
	public static final String MODEL_BUY_LONG_MINUTE01_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.MACD.THRESHOLD";
	public static final String MODEL_BUY_LONG_MINUTE01_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.MACD.USE_PERIODS";
	public static final String MODEL_BUY_LONG_MINUTE01_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_LONG_MINUTE01_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.MIN01.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_LONG_EXIT_BUCKET_EXIT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.LONG.EXIT_BUCKET_EXIT";

	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// ----------------------------------------------- SELL LONG StrategyDto Configuration Parameters -------------------------------------------------
	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// SELL LONG Parameters - DAILY
	public static final String MODEL_SELL_LONG_DAILY_HIGHPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.GAUGE";
	public static final String MODEL_SELL_LONG_DAILY_HIGHPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.NUMPERIODSFORHIGHPT";

	public static final String MODEL_SELL_LONG_DAILY_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.USE_MOMENTUM";
	public static final String MODEL_SELL_LONG_DAILY_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.MOMENTUM_TYPE";
	public static final String MODEL_SELL_LONG_DAILY_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_LONG_DAILY_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.SLOPE.USE";
	public static final String MODEL_SELL_LONG_DAILY_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_LONG_DAILY_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.MACD.USE";
	public static final String MODEL_SELL_LONG_DAILY_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.MACD.THRESHOLD";
	public static final String MODEL_SELL_LONG_DAILY_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.MACD.USE_PERIODS";
	public static final String MODEL_SELL_LONG_DAILY_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_LONG_DAILY_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_LONG_DAILY_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.EXIT_TIMEFRAME";

	// -------------------------------- DAILY - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_LONG_DAILY_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_LONG_DAILY_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_LONG_DAILY_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.DAILY.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL LONG Parameters - MIN60
	public static final String MODEL_SELL_LONG_MINUTE60_MAX_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MAXPERIODSINBUCKET";

	public static final String MODEL_SELL_LONG_MINUTE60_HIGHPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.GAUGE";
	public static final String MODEL_SELL_LONG_MINUTE60_HIGHPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.NUMPERIODSFORHIGHPT";

	public static final String MODEL_SELL_LONG_MINUTE60_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.USE_MOMENTUM";
	public static final String MODEL_SELL_LONG_MINUTE60_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MOMENTUM_TYPE";
	public static final String MODEL_SELL_LONG_MINUTE60_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_LONG_MINUTE60_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.SLOPE.USE";
	public static final String MODEL_SELL_LONG_MINUTE60_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_LONG_MINUTE60_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MACD.USE";
	public static final String MODEL_SELL_LONG_MINUTE60_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MACD.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE60_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MACD.USE_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE60_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_LONG_MINUTE60_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_LONG_MINUTE60_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.EXIT_TIMEFRAME";

	// -------------------------------- MINUTE 60 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_LONG_MINUTE60_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE60_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE60_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN60.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL LONG Parameters - MIN15
	public static final String MODEL_SELL_LONG_MINUTE15_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.USE_MOMENTUM";
	public static final String MODEL_SELL_LONG_MINUTE15_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.MOMENTUM_TYPE";
	public static final String MODEL_SELL_LONG_MINUTE15_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_LONG_MINUTE15_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.SLOPE.USE";
	public static final String MODEL_SELL_LONG_MINUTE15_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_LONG_MINUTE15_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.MACD.USE";
	public static final String MODEL_SELL_LONG_MINUTE15_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.MACD.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE15_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.MACD.USE_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE15_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_LONG_MINUTE15_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_LONG_MINUTE15_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.EXIT_TIMEFRAME";

	// -------------------------------- MINUTE15 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_LONG_MINUTE15_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE15_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE15_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN15.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL LONG Parameters - MIN05
	public static final String MODEL_SELL_LONG_MINUTE05_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.USE_MOMENTUM";
	public static final String MODEL_SELL_LONG_MINUTE05_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.MOMENTUM_TYPE";
	public static final String MODEL_SELL_LONG_MINUTE05_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_LONG_MINUTE05_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.PRICELAGPERIODS";
	public static final String MODEL_SELL_LONG_USE_MINUTE01 = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.USE_MIN01";

	public static final String MODEL_SELL_LONG_MINUTE05_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.SLOPE.USE";
	public static final String MODEL_SELL_LONG_MINUTE05_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_LONG_MINUTE05_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.MACD.USE";
	public static final String MODEL_SELL_LONG_MINUTE05_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.MACD.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE05_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.MACD.USE_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE05_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_LONG_MINUTE05_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.MACD.USE_SIGNAL";

	// -------------------------------- MINUTE05 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_LONG_MINUTE05_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE05_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE05_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN05.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL LONG Parameters - MIN01
	public static final String MODEL_SELL_LONG_MINUTE01_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.USE_MOMENTUM";
	public static final String MODEL_SELL_LONG_MINUTE01_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.MOMENTUM_TYPE";
	public static final String MODEL_SELL_LONG_MINUTE01_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.MOMENTUM_THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE01_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.PRICELAGPERIODS";

	public static final String MODEL_SELL_LONG_MINUTE01_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.SLOPE.USE";
	public static final String MODEL_SELL_LONG_MINUTE01_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_LONG_MINUTE01_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.MACD.USE";
	public static final String MODEL_SELL_LONG_MINUTE01_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.MACD.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE01_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.MACD.USE_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE01_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_LONG_MINUTE01_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_LONG_PROFIT_TAKING_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.PROFIT_TAKING_THRESHOLD";
	public static final String MODEL_SELL_LONG_PROFIT_TAKING_SUCCESS_PERCENT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.PROFIT_TAKING_SUCCESS_PERCENT_THRESHOLD";
	public static final String MODEL_SELL_LONG_PROFIT_TAKING_POSITION_PERCENT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.PROFIT_TAKING_POSITION_PERCENT_THRESHOLD";

	// -------------------------------- MINUTE01 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_LONG_MINUTE01_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_LONG_MINUTE01_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_LONG_MINUTE01_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.LONG.MIN01.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// ----------------------------------------------- BUY SHORT Strategy Configuration Parameters -------------------------------------------------
	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// BUY SHORT Parameters - DAILY
	public static final String MODEL_BUY_SHORT_DAILY_MAX_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MAXPERIODSINBUCKET";

	public static final String MODEL_BUY_SHORT_DAILY_HIGHPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.GAUGE";
	public static final String MODEL_BUY_SHORT_DAILY_HIGHPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.NUMPERIODSFORHIGHPT";

	public static final String MODEL_BUY_SHORT_DAILY_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.USE_MOMENTUM";
	public static final String MODEL_BUY_SHORT_DAILY_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MOMENTUM_TYPE";
	public static final String MODEL_BUY_SHORT_DAILY_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_SHORT_DAILY_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.SLOPE.USE";
	public static final String MODEL_BUY_SHORT_DAILY_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_SHORT_DAILY_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MACD.USE";
	public static final String MODEL_BUY_SHORT_DAILY_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MACD.THRESHOLD";
	public static final String MODEL_BUY_SHORT_DAILY_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MACD.USE_PERIODS";
	public static final String MODEL_BUY_SHORT_DAILY_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_SHORT_DAILY_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_SHORT_DAILY_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.EXIT_TIMEFRAME";

	public static final String MODEL_BUY_SHORT_DAILY_834_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.USE";
	public static final String MODEL_BUY_SHORT_DAILY_834_FILTER_SPIKES = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.FILTER_SPIKES";
	public static final String MODEL_BUY_SHORT_DAILY_834_EMA8_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.EMA8_PERIODS";
	public static final String MODEL_BUY_SHORT_DAILY_834_SMA14_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.SMA14_PERIODS";
	public static final String MODEL_BUY_SHORT_DAILY_834_SMA20_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.SMA20_PERIODS";
	public static final String MODEL_BUY_SHORT_DAILY_834_EMA34_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.EMA34_PERIODS";
	public static final String MODEL_BUY_SHORT_DAILY_834_SMA20_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.SMA20_STOPLOSS_PERIODS";
	public static final String MODEL_BUY_SHORT_DAILY_834_EMA34_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.EMA34_STOPLOSS_PERIODS";
	public static final String MODEL_BUY_SHORT_DAILY_834_WAIT_PERIODS_SINCE_SOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.WAIT_PERIODS_SINCE_SOLD";
	public static final String MODEL_BUY_SHORT_DAILY_834_WAIT_PERIODS_CONFIRM34 = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.WAIT_PERIODS_CONFIRM34";
	public static final String MODEL_BUY_SHORT_DAILY_834_CONFIRM_PRICE_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.CONFIRM_PRICE_PERCENT";

	public static final String MODEL_BUY_SHORT_DAILY_834_ONENTRY_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.ONENTRY_ORDER_PERCENT";
	public static final String MODEL_BUY_SHORT_DAILY_834_ONCONFIRM_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.DAILY.STRATEGY_834.ONCONFIRM_ORDER_PERCENT";

	// BUY SHORT Parameters - MIN60
	public static final String MODEL_BUY_SHORT_MINUTE60_MAX_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MAXPERIODSINBUCKET";

	public static final String MODEL_BUY_SHORT_MINUTE60_HIGHPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.GAUGE";
	public static final String MODEL_BUY_SHORT_MINUTE60_HIGHPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.NUMPERIODSFORHIGHPT";

	public static final String MODEL_BUY_SHORT_MINUTE60_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.USE_MOMENTUM";
	public static final String MODEL_BUY_SHORT_MINUTE60_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MOMENTUM_TYPE";
	public static final String MODEL_BUY_SHORT_MINUTE60_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_SHORT_MINUTE60_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.SLOPE.USE";
	public static final String MODEL_BUY_SHORT_MINUTE60_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_SHORT_MINUTE60_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MACD.USE";
	public static final String MODEL_BUY_SHORT_MINUTE60_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MACD.THRESHOLD";
	public static final String MODEL_BUY_SHORT_MINUTE60_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MACD.USE_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE60_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_SHORT_MINUTE60_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_SHORT_MINUTE60_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.EXIT_TIMEFRAME";

	public static final String MODEL_BUY_SHORT_MINUTE60_834_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.USE";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_FILTER_SPIKES = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.FILTER_SPIKES";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_EMA8_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.EMA8_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_SMA14_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.SMA14_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_SMA20_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.SMA20_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_EMA34_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.EMA34_PERIODS";

	public static final String MODEL_BUY_SHORT_MINUTE60_834_SMA20_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.SMA20_STOPLOSS_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_EMA34_STOPLOSS_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.EMA34_STOPLOSS_PERIODS";

	public static final String MODEL_BUY_SHORT_MINUTE60_834_WAIT_PERIODS_SINCE_SOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.WAIT_PERIODS_SINCE_SOLD";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_WAIT_PERIODS_CONFIRM34 = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.WAIT_PERIODS_CONFIRM34";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_CONFIRM_PRICE_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.CONFIRM_PRICE_PERCENT";

	public static final String MODEL_BUY_SHORT_MINUTE60_834_ONENTRY_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.ONENTRY_ORDER_PERCENT";
	public static final String MODEL_BUY_SHORT_MINUTE60_834_ONCONFIRM_ORDER_PERCENT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN60.STRATEGY_834.ONCONFIRM_ORDER_PERCENT";

	// BUY SHORT Parameters - MIN15
	public static final String MODEL_BUY_SHORT_MINUTE15_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.USE_MOMENTUM";
	public static final String MODEL_BUY_SHORT_MINUTE15_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.MOMENTUM_TYPE";
	public static final String MODEL_BUY_SHORT_MINUTE15_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.MOMENTUM_THRESHOLD";
	public static final String MODEL_BUY_SHORT_MINUTE15_MOMENTUM_EXIT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.EXIT_MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_SHORT_MINUTE15_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.SLOPE.USE";
	public static final String MODEL_BUY_SHORT_MINUTE15_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_SHORT_MINUTE15_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.MACD.USE";
	public static final String MODEL_BUY_SHORT_MINUTE15_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.MACD.THRESHOLD";
	public static final String MODEL_BUY_SHORT_MINUTE15_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.MACD.USE_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE15_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_SHORT_MINUTE15_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_SHORT_MINUTE15_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN15.EXIT_TIMEFRAME";

	// BUY SHORT Parameters - MIN05
	public static final String MODEL_BUY_SHORT_MINUTE05_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.USE_MOMENTUM";
	public static final String MODEL_BUY_SHORT_MINUTE05_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.MOMENTUM_TYPE";
	public static final String MODEL_BUY_SHORT_MINUTE05_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.MOMENTUM_THRESHOLD";
	public static final String MODEL_BUY_SHORT_MINUTE05_MOMENTUM_EXIT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.EXIT_MOMENTUM_THRESHOLD";

	public static final String MODEL_BUY_SHORT_MINUTE05_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.PRICELAGPERIODS";
	public static final String MODEL_BUY_SHORT_USE_MINUTE01 = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.USE_MIN01";

	public static final String MODEL_BUY_SHORT_MINUTE05_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.SLOPE.USE";
	public static final String MODEL_BUY_SHORT_MINUTE05_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_SHORT_MINUTE05_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.MACD.USE";
	public static final String MODEL_BUY_SHORT_MINUTE05_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.MACD.THRESHOLD";
	public static final String MODEL_BUY_SHORT_MINUTE05_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.MACD.USE_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE05_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_SHORT_MINUTE05_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN05.MACD.USE_SIGNAL";

	// BUY SHORT Parameters - MIN01
	public static final String MODEL_BUY_SHORT_MINUTE01_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.USE_MOMENTUM";
	public static final String MODEL_BUY_SHORT_MINUTE01_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.MOMENTUM_TYPE";
	public static final String MODEL_BUY_SHORT_MINUTE01_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.MOMENTUM_THRESHOLD";
	public static final String MODEL_BUY_SHORT_MINUTE01_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.PRICELAGPERIODS";

	public static final String MODEL_BUY_SHORT_MINUTE01_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.SLOPE.USE";
	public static final String MODEL_BUY_SHORT_MINUTE01_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.SLOPE.THRESHOLD";

	public static final String MODEL_BUY_SHORT_MINUTE01_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.MACD.USE";
	public static final String MODEL_BUY_SHORT_MINUTE01_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.MACD.THRESHOLD";
	public static final String MODEL_BUY_SHORT_MINUTE01_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.MACD.USE_PERIODS";
	public static final String MODEL_BUY_SHORT_MINUTE01_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_BUY_SHORT_MINUTE01_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.MIN01.MACD.USE_SIGNAL";

	public static final String MODEL_BUY_SHORT_EXIT_BUCKET_EXIT = "DV:XML.MODEL.MKTD.STRATEGY.BUY.SHORT.EXIT_BUCKET_EXIT";

	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// ----------------------------------------------- SELL SHORT StrategyDto Configuration Parameters ------------------------------------------------
	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// SELL SHORT Parameters - DAILY
	public static final String MODEL_SELL_SHORT_DAILY_LOWPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.GAUGE";
	public static final String MODEL_SELL_SHORT_DAILY_LOWPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.NUMPERIODSFORLOWPT";

	public static final String MODEL_SELL_SHORT_DAILY_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.USE_MOMENTUM";
	public static final String MODEL_SELL_SHORT_DAILY_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.MOMENTUM_TYPE";
	public static final String MODEL_SELL_SHORT_DAILY_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_SHORT_DAILY_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.SLOPE.USE";
	public static final String MODEL_SELL_SHORT_DAILY_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_SHORT_DAILY_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.MACD.USE";
	public static final String MODEL_SELL_SHORT_DAILY_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.MACD.THRESHOLD";
	public static final String MODEL_SELL_SHORT_DAILY_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.MACD.USE_PERIODS";
	public static final String MODEL_SELL_SHORT_DAILY_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_SHORT_DAILY_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_SHORT_DAILY_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.EXIT_TIMEFRAME";

	// -------------------------------- DAILY - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_SHORT_DAILY_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_SHORT_DAILY_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_SHORT_DAILY_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.DAILY.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL SHORT Parameters - MIN60
	public static final String MODEL_SELL_SHORT_MINUTE60_MAX_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MAXPERIODSINBUCKET";

	public static final String MODEL_SELL_SHORT_MINUTE60_LOWPT_GAUGE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.GAUGE";
	public static final String MODEL_SELL_SHORT_MINUTE60_LOWPT_NUMPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.NUMPERIODSFORLOWPT";

	public static final String MODEL_SELL_SHORT_MINUTE60_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.USE_MOMENTUM";
	public static final String MODEL_SELL_SHORT_MINUTE60_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MOMENTUM_TYPE";
	public static final String MODEL_SELL_SHORT_MINUTE60_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE60_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.SLOPE.USE";
	public static final String MODEL_SELL_SHORT_MINUTE60_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE60_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MACD.USE";
	public static final String MODEL_SELL_SHORT_MINUTE60_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MACD.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE60_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MACD.USE_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE60_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_SHORT_MINUTE60_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_SHORT_MINUTE60_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.EXIT_TIMEFRAME";

	// -------------------------------- MINUTE60 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_SHORT_MINUTE60_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE60_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE60_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN60.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL SHORT Parameters - MIN15
	public static final String MODEL_SELL_SHORT_MINUTE15_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.USE_MOMENTUM";
	public static final String MODEL_SELL_SHORT_MINUTE15_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.MOMENTUM_TYPE";
	public static final String MODEL_SELL_SHORT_MINUTE15_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE15_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.SLOPE.USE";
	public static final String MODEL_SELL_SHORT_MINUTE15_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE15_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.MACD.USE";
	public static final String MODEL_SELL_SHORT_MINUTE15_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.MACD.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE15_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.MACD.USE_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE15_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_SHORT_MINUTE15_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_SHORT_MINUTE15_EXIT_TIMEFRAME = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.EXIT_TIMEFRAME";

	// -------------------------------- MINUTE15 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_SHORT_MINUTE15_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE15_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE15_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN15.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL SHORT Parameters - MIN05
	public static final String MODEL_SELL_SHORT_MINUTE05_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.USE_MOMENTUM";
	public static final String MODEL_SELL_SHORT_MINUTE05_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.MOMENTUM_TYPE";
	public static final String MODEL_SELL_SHORT_MINUTE05_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE05_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.PRICELAGPERIODS";
	public static final String MODEL_SELL_SHORT_USE_MINUTE01 = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.USE_MIN01";

	public static final String MODEL_SELL_SHORT_MINUTE05_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.SLOPE.USE";
	public static final String MODEL_SELL_SHORT_MINUTE05_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE05_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.MACD.USE";
	public static final String MODEL_SELL_SHORT_MINUTE05_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.MACD.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE05_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.MACD.USE_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE05_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_SHORT_MINUTE05_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.MACD.USE_SIGNAL";

	// -------------------------------- MINUTE 5 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_SHORT_MINUTE05_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE05_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE05_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN05.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// SELL SHORT Parameters - MIN01
	public static final String MODEL_SELL_SHORT_MINUTE01_USE_MOMENTUM = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.USE_MOMENTUM";
	public static final String MODEL_SELL_SHORT_MINUTE01_MOMENTUM_TYPE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.MOMENTUM_TYPE";
	public static final String MODEL_SELL_SHORT_MINUTE01_MOMENTUM_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.MOMENTUM_THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE01_PRICELAGPERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.PRICELAGPERIODS";

	public static final String MODEL_SELL_SHORT_MINUTE01_SLOPE_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.SLOPE.USE";
	public static final String MODEL_SELL_SHORT_MINUTE01_SLOPE_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.SLOPE.THRESHOLD";

	public static final String MODEL_SELL_SHORT_MINUTE01_MACD_USE = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.MACD.USE";
	public static final String MODEL_SELL_SHORT_MINUTE01_MACD_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.MACD.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE01_MACD_USE_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.MACD.USE_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE01_MACD_PERIODS_CONSTANT = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.MACD.NUM_PERIODS_CONSTANT";
	public static final String MODEL_SELL_SHORT_MINUTE01_MACD_USE_SIGNAL = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.MACD.USE_SIGNAL";

	public static final String MODEL_SELL_SHORT_PROFIT_TAKING_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.PROFIT_TAKING_THRESHOLD";
	public static final String MODEL_SELL_SHORT_PROFIT_TAKING_SUCCESS_PERCENT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.PROFIT_TAKING_SUCCESS_PERCENT_THRESHOLD";
	public static final String MODEL_SELL_SHORT_PROFIT_TAKING_POSITION_PERCENT_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.PROFIT_TAKING_POSITION_PERCENT_THRESHOLD";

	// -------------------------------- MINUTE 1 - PAIN STRATEGY ----------------------------------------------
	public static final String MODEL_SELL_SHORT_MINUTE01_PAIN_THRESHOLD = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.PAIN_STRATEGY.THRESHOLD";
	public static final String MODEL_SELL_SHORT_MINUTE01_PAIN_REENTRY_PERIODS = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.PAIN_STRATEGY.RETRY_PERIODS";
	public static final String MODEL_SELL_SHORT_MINUTE01_PAIN_SPIKE_FILTERING = "DV:XML.MODEL.MKTD.STRATEGY.SELL.SHORT.MIN01.PAIN_STRATEGY.USE_SPIKE_FILTERING";

	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// -------------------------------------------------------- HARVESTER --------------------------------------------------------------------------
	// ---------------------------------------------------------------------------------------------------------------------------------------------
	public static final String MODEL_HARVESTER_SERVICE_TIME = "DV:XML.MODEL.APPLICATION.HARVESTER.SERVICE_TIME";
	public static final String MODEL_HARVESTER_EMAIL_RECIPIENTS = "DV:XML.MODEL.APPLICATION.HARVESTER.EMAIL_RECIPIENTS";

	public static final String MODEL_HARVESTER_ON_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.IS_ENABLED";
	public static final String MODEL_HARVESTER_ON_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.IS_ENABLED";

	public static final String MODEL_HARVESTER_MIN_STOCK_PRICE_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.MIN_STOCK_PRICE";
	public static final String MODEL_HARVESTER_MAX_STOCK_PRICE_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.MAX_STOCK_PRICE";
	public static final String MODEL_HARVESTER_MIN_STOCK_VOLUME_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.MIN_STOCK_VOLUME";
	public static final String MODEL_HARVESTER_MOMENTUM_THRESHOLD_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.MOMENTUM_THRESHOLD";
	public static final String MODEL_HARVESTER_PRICE_THRESHOLD_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.PRICE_THRESHOLD";

	public static final String MODEL_HARVESTER_MIN_STOCK_PRICE_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.MIN_STOCK_PRICE";
	public static final String MODEL_HARVESTER_MAX_STOCK_PRICE_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.MAX_STOCK_PRICE";
	public static final String MODEL_HARVESTER_MIN_STOCK_VOLUME_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.MIN_STOCK_VOLUME";
	public static final String MODEL_HARVESTER_MOMENTUM_THRESHOLD_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.MOMENTUM_THRESHOLD";
	public static final String MODEL_HARVESTER_PRICE_THRESHOLD_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.PRICE_THRESHOLD";

	// this is the number of years of data to get. (Currently not used):
	public static final String MODEL_HARVESTER_NUM_YEARS_PRICE_HISTORY_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.NUM_YEARS_PRICE_HISTORY";
	public static final String MODEL_HARVESTER_NUM_YEARS_PRICE_HISTORY_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.NUM_YEARS_PRICE_HISTORY";

	// this is the timeframe to use: daily, weekly, monthly. (Currently not used):
	public static final String HARVESTER_HIGH_LOW_TIMEPERIOD_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.HIGH_LOW_TIMEPERIOD";
	public static final String HARVESTER_HIGH_LOW_TIMEPERIOD_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.HIGH_LOW_TIMEPERIOD";

	public static final String MODEL_HARVESTER_NUM_YEARS_ON_THE_MARKET = "DV:XML.MODEL.APPLICATION.HARVESTER.NUM_YEARS_ON_THE_MARKET";

	// --------------------------------------- V7.5 LONG HARVESTER -------------------------------------
	public static final String MODEL_HARVESTER_8_OVER_14_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.8_OVER_14";
	public static final String MODEL_HARVESTER_8_OVER_14_8EMA_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.8_OVER_14_8EMA";
	public static final String MODEL_HARVESTER_8_OVER_14_14SMA_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.8_OVER_14_14SMA";
	public static final String MODEL_HARVESTER_8_OVER_34_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.8_OVER_34";
	public static final String MODEL_HARVESTER_8_OVER_34_8EMA_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.8_OVER_34_8EMA";

	public static final String MODEL_HARVESTER_8_OVER_34_34EMA_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.8_OVER_34_34EMA";
	public static final String MODEL_HARVESTER_PRICE_OVER_34_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.PRICE_OVER_34";
	public static final String MODEL_HARVESTER_PRICE_OVER_34_34EMA_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.PRICE_OVER_34_34EMA";
	public static final String MODEL_HARVESTER_PRICE_CONFIRMED_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.PRICE_CONFIRMED";
	public static final String MODEL_HARVESTER_MAS_ALIGNED_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.MAS_ALIGNED";

	public static final String MODEL_HARVESTER_OVER_200_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.OVER_200";
	public static final String MODEL_HARVESTER_OVER_200_200SMA_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.OVER_200_200SMA";
	public static final String MODEL_HARVESTER_RISING_200_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.RISING_200";
	public static final String MODEL_HARVESTER_OVER_50_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.OVER_50";
	public static final String MODEL_HARVESTER_OVER_50_50SMA_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.OVER_50_50SMA";

	public static final String MODEL_HARVESTER_RISING_50_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.RISING_50";
	public static final String MODEL_HARVESTER_USE_ONLY_USD_USDT_LONG = "DV:XML.MODEL.APPLICATION.HARVESTER.LONG.USE_ONLY_USD_USDT";

	// --------------------------------------- V7.5 SHORT HARVESTER -------------------------------------
	public static final String MODEL_HARVESTER_8_UNDER_14_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.8_UNDER_14";
	public static final String MODEL_HARVESTER_8_UNDER_14_8EMA_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.8_UNDER_14_8EMA";
	public static final String MODEL_HARVESTER_8_UNDER_14_14SMA_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.8_UNDER_14_14SMA";
	public static final String MODEL_HARVESTER_8_UNDER_34_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.8_UNDER_34";
	public static final String MODEL_HARVESTER_8_UNDER_34_8EMA_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.8_UNDER_34_8EMA";

	public static final String MODEL_HARVESTER_8_UNDER_34_34EMA_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.8_UNDER_34_34EMA";
	public static final String MODEL_HARVESTER_PRICE_UNDER_34_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.PRICE_UNDER_34";
	public static final String MODEL_HARVESTER_PRICE_UNDER_34_34EMA_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.PRICE_UNDER_34_34EMA";
	public static final String MODEL_HARVESTER_PRICE_CONFIRMED_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.PRICE_CONFIRMED";
	public static final String MODEL_HARVESTER_MAS_ALIGNED_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.MAS_ALIGNED";

	public static final String MODEL_HARVESTER_UNDER_200_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.UNDER_200";
	public static final String MODEL_HARVESTER_UNDER_200_200SMA_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.UNDER_200_200SMA";
	public static final String MODEL_HARVESTER_FALLING_200_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.FALLING_200";
	public static final String MODEL_HARVESTER_UNDER_50_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.UNDER_50";
	public static final String MODEL_HARVESTER_UNDER_50_50SMA_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.UNDER_50_50SMA";

	public static final String MODEL_HARVESTER_FALLING_50_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.FALLING_50";
	public static final String MODEL_HARVESTER_USE_ONLY_USD_USDT_SHORT = "DV:XML.MODEL.APPLICATION.HARVESTER.SHORT.USE_ONLY_USD_USDT";

	// ---------------------------------------------------------------------------------------------------------------------------------------------
	// ------------------------------------------------ DROP CAT PARAMETERS ------------------------------------------------------------------------
	// ---------------------------------------------------------------------------------------------------------------------------------------------
	public static final String MODEL_DROP_CAT = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT";
	public static final String MODEL_DROP_CAT_SELL_END_OF_DAY = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_SELL_END_OF_DAY";
	public static final String MODEL_DROP_CAT_DOUBLE_DOWN_ON_TRAP = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_DOUBLE_DOWN_ON_TRAP";

	public static final String MODEL_DROP_CAT_TIME_THRESHOLD_LONG = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_TIME_THRESHOLD_LONG";
	public static final String MODEL_DROP_CAT_TIME_THRESHOLD_SHORT = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_TIME_THRESHOLD_SHORT";

	public static final String MODEL_DROP_CAT_TRAP_PERCENT_LOSS_LONG = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_TRAP_PERCENT_LOSS_LONG";
	public static final String MODEL_DROP_CAT_TRAP_PERCENT_LOSS_SHORT = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_TRAP_PERCENT_LOSS_SHORT";
	public static final float DROP_CAT_TRAP_PERCENT_LOSS_DEFAULT = 1.5f;

	public static final String MODEL_DROP_CAT_TRAP_NUM_MINUTES_LONG = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_TRAP_NUM_MINUTES_LONG";
	public static final String MODEL_DROP_CAT_TRAP_NUM_MINUTES_SHORT = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_TRAP_NUM_MINUTES_SHORT";
	public static final int DROP_CAT_TRAP_NUM_MINUTES_DEFAULT = 4;

	public static final String MODEL_DROP_CAT_MIN15_THRESHOLD_LONG = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_MIN15_THRESHOLD_LONG";
	public static final String MODEL_DROP_CAT_MIN15_THRESHOLD_SHORT = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_MIN15_THRESHOLD_SHORT";

	public static final String MODEL_DROP_CAT_MIN05_THRESHOLD_LONG = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_MIN05_THRESHOLD_LONG";
	public static final String MODEL_DROP_CAT_MIN05_THRESHOLD_SHORT = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_MIN05_THRESHOLD_SHORT";

	public static final String MODEL_DROP_CAT_PAIN_THRESHOLD_LONG = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_PAIN_THRESHOLD_LONG";
	public static final String MODEL_DROP_CAT_PAIN_THRESHOLD_SHORT = "DV:XML.MODEL.MKTD.SCENARIO.DROP_CAT_PAIN_THRESHOLD_SHORT";
	public static final float DROP_CAT_PAIN_THRESHOLD_DEFAULT = 0.5f;

	// ------------------------------------------------ REJECTED LISTS PARAMETERS -----------------------------------------------
	public static final String ACCTCONFIG_REJECTED_PERMANENT_AGING_NUM_PERIODS_LONG = "DV:XML.MODEL.MKTD.ACCTCONFIG.REJECTED_PERMANENT_AGING_NUM_PERIODS_LONG";
	public static final String ACCTCONFIG_REJECTED_PERMANENT_AGING_NUM_PERIODS_SHORT = "DV:XML.MODEL.MKTD.ACCTCONFIG.REJECTED_PERMANENT_AGING_NUM_PERIODS_SHORT";

	public static final String ACCTCONFIG_REJECTED_DISMISSABLE_AGING_NUM_PERIODS_LONG = "DV:XML.MODEL.MKTD.ACCTCONFIG.REJECTED_DISMISSABLE_AGING_NUM_PERIODS_LONG";
	public static final String ACCTCONFIG_REJECTED_DISMISSABLE_AGING_NUM_PERIODS_SHORT = "DV:XML.MODEL.MKTD.ACCTCONFIG.REJECTED_DISMISSABLE_AGING_NUM_PERIODS_SHORT";

	public static final boolean is24HourExchange() {
		if ("0".equals(Config.getValue(ConfigStrategy.MODEL_USE_24_HOUR_EXCHANGES)))
			return false;
		else
			return true;
	}
}
