services:
  mysqlapp:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: jeb
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
#    volumes:
#      - pgdata:/var/lib/mysql/data
    networks:
      springboot-mysql-net:
  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - mysqlapp
    environment:
      LIQUIBASE_URL: jdbc:mysql://mysql:3306/mydb
      LIQUIBASE_USERNAME: root
      LIQUIBASE_PASSWORD: your_root_password
      LIQUIBASE_CHANGELOG_FILE: db/changelog/db.changelog-master.yaml
    volumes:
      - ./db/changelog:/db/changelog
    command: update
  my-web-app:
    container_name: greenmark
    build: .
    ports:
        - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/mydb
      - spring.datasource.username=jeb
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqlapp
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net: