/* Generated by Together */

package com.greenmark.common.exception;

/**
 * @formatter:off
 * <p>Copyright: Copyright (c) 2021</p>
 * <p>Company: Greenman Financial Services, Inc.</p>
 *  
 * <p>Title: MultipleAttemptsException</p>
 * <p>Description: This exception is used by the Prices DB Updater application if it fails to retrieve data from the external datafeed service and must make another attempt.</p>
 *
 * @author Monte Seibel
 * @version 7.0
 * @formatter:on
 */

public class MultipleAttemptsException extends Exception {
    public static final String CLASSNAME = "MultipleAttemptsException";

    private static final long serialVersionUID = 1L;

    /**
     * The message that will be included in this exception for display to the user.
     */
    protected String message;

    public MultipleAttemptsException() {
    }

    /**
     * This constructor creates an MultipleAttemptsException object and initializes its message attribute with the input messageString parameter.
     *
     * @param messageString Any message that will be included in this exception for display to the user.
     * @return This Object
     */
    public MultipleAttemptsException(String messageString) {
        message = messageString;
    }

    /**
     * Public accessor to set the exception's message string.
     */
    public final String getMessage() {
        return message;
    }

    /**
     * Public accessor to return the exception's message string.
     */
    public final void setMessage(String newMessageString) {
        message = newMessageString;
    }
}
