spring:
  application:
    name: Greenmark
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/greenmark
    username: jeb
  jpa:
    show-sql: false
  mail:
    host: smtp.gmail.com
    password: t2Z7qIUHhx!PJuN&
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: 'true'
    username: jeb.seibel@gmail.com
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: mypass
      timeout: 600000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
finnhub:
  token: cq63eipr01qlbj4vp9j0cq63eipr01qlbj4vp9jg
  waitTimeInSeconds: 1
  limitPerSecond: 30
logging:
  level:
    com:
      greenmark: INFO
    root: INFO
model:
  minute01:
    promote: 80
    demote: 20
  minute05:
    promote: 80
    demote: 20
  minute15:
    promote: 80
    demote: 20
  minute60:
    promote: 80
    demote: 20
  daily:
    promote: 80
    demote: 20
  all:
    promote: 80
    demote: 20
thread-pool: 12