email: test@mkyong.com
finnhub:
  token: cq63eipr01qlbj4vp9j0cq63eipr01qlbj4vp9jg
  waitTimeInSeconds: 1
  limitPerSecond: 30
logging:
  level:
    com:
      greenmark: INFO
    root: INFO
message-from-application-properties: Hello from application.properties
model:
  minute60:
    promote: 11.0
    demote: 9.0


  stock-max-price: 100
  stock-min-price: 10
spring:
  application:
    name: DataFeed
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/greenmark
    username: jeb
  jpa:
    show-sql: false
thread-pool: 12