email: test@mkyong.com
finnhub:
  token: cq63eipr01qlbj4vp9j0cq63eipr01qlbj4vp9jg
  waitTimeInSeconds: 1
  limitPerSecond: 30
logging:
  level:
    com:
      greenmark: INFO
    root: INFO
model:
  minute01:
    promote: 11.1
    demote: 22.2
  minute05:
    promote: 11
    demote: 22
  minute15:
    promote: 11
    demote: 22
  minute60:
    promote: 11
    demote: 22
  daily:
    promote: 11
    demote: 22
  all:
    promote: 11
    demote: 22
spring:
  application:
    name: DataFeed
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/greenmark
    username: jeb
  jpa:
    show-sql: false
thread-pool: 12