/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.greenmark.datafeed.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * InstitutionalPortfolio
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class InstitutionalPortfolio {
  @SerializedName("name")
  private String name = null;

  @SerializedName("cik")
  private String cik = null;

  @SerializedName("data")
  private List<InstitutionalPortfolioGroup> data = null;

  public InstitutionalPortfolio name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Investor&#x27;s name.
   * @return name
  **/
  @Schema(description = "Investor's name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InstitutionalPortfolio cik(String cik) {
    this.cik = cik;
    return this;
  }

   /**
   * CIK.
   * @return cik
  **/
  @Schema(description = "CIK.")
  public String getCik() {
    return cik;
  }

  public void setCik(String cik) {
    this.cik = cik;
  }

  public InstitutionalPortfolio data(List<InstitutionalPortfolioGroup> data) {
    this.data = data;
    return this;
  }

  public InstitutionalPortfolio addDataItem(InstitutionalPortfolioGroup dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<InstitutionalPortfolioGroup>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Array of positions.
   * @return data
  **/
  @Schema(description = "Array of positions.")
  public List<InstitutionalPortfolioGroup> getData() {
    return data;
  }

  public void setData(List<InstitutionalPortfolioGroup> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstitutionalPortfolio institutionalPortfolio = (InstitutionalPortfolio) o;
    return Objects.equals(this.name, institutionalPortfolio.name) &&
        Objects.equals(this.cik, institutionalPortfolio.cik) &&
        Objects.equals(this.data, institutionalPortfolio.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, cik, data);
  }


  @Override
  public String toString() {

      String sb = "class InstitutionalPortfolio {\n" +
              "    name: " + toIndentedString(name) + "\n" +
              "    cik: " + toIndentedString(cik) + "\n" +
              "    data: " + toIndentedString(data) + "\n" +
              "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
