/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.greenmark.datafeed.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * IsinChangeInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class IsinChangeInfo {
    @SerializedName("atDate")
    private String atDate = null;

    @SerializedName("oldIsin")
    private String oldIsin = null;

    @SerializedName("newIsin")
    private String newIsin = null;

    public IsinChangeInfo atDate(String atDate) {
        this.atDate = atDate;
        return this;
    }

    /**
     * Event&#x27;s date.
     *
     * @return atDate
     **/
    @Schema(description = "Event's date.")
    public String getAtDate() {
        return atDate;
    }

    public void setAtDate(String atDate) {
        this.atDate = atDate;
    }

    public IsinChangeInfo oldIsin(String oldIsin) {
        this.oldIsin = oldIsin;
        return this;
    }

    /**
     * Old ISIN.
     *
     * @return oldIsin
     **/
    @Schema(description = "Old ISIN.")
    public String getOldIsin() {
        return oldIsin;
    }

    public void setOldIsin(String oldIsin) {
        this.oldIsin = oldIsin;
    }

    public IsinChangeInfo newIsin(String newIsin) {
        this.newIsin = newIsin;
        return this;
    }

    /**
     * New ISIN.
     *
     * @return newIsin
     **/
    @Schema(description = "New ISIN.")
    public String getNewIsin() {
        return newIsin;
    }

    public void setNewIsin(String newIsin) {
        this.newIsin = newIsin;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IsinChangeInfo isinChangeInfo = (IsinChangeInfo) o;
        return Objects.equals(this.atDate, isinChangeInfo.atDate) &&
                Objects.equals(this.oldIsin, isinChangeInfo.oldIsin) &&
                Objects.equals(this.newIsin, isinChangeInfo.newIsin);
    }

    @Override
    public int hashCode() {
        return Objects.hash(atDate, oldIsin, newIsin);
    }


    @Override
    public String toString() {

        String sb = "class IsinChangeInfo {\n" +
                "    atDate: " + toIndentedString(atDate) + "\n" +
                "    oldIsin: " + toIndentedString(oldIsin) + "\n" +
                "    newIsin: " + toIndentedString(newIsin) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
