/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.greenmark.datafeed.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PatternRecognition
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class PatternRecognition {
    @SerializedName("points")
    private List<ScanPattern> points = null;

    public PatternRecognition points(List<ScanPattern> points) {
        this.points = points;
        return this;
    }

    public PatternRecognition addPointsItem(ScanPattern pointsItem) {
        if (this.points == null) {
            this.points = new ArrayList<ScanPattern>();
        }
        this.points.add(pointsItem);
        return this;
    }

    /**
     * Array of patterns.
     *
     * @return points
     **/
    @Schema(description = "Array of patterns.")
    public List<ScanPattern> getPoints() {
        return points;
    }

    public void setPoints(List<ScanPattern> points) {
        this.points = points;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatternRecognition patternRecognition = (PatternRecognition) o;
        return Objects.equals(this.points, patternRecognition.points);
    }

    @Override
    public int hashCode() {
        return Objects.hash(points);
    }


    @Override
    public String toString() {

        String sb = "class PatternRecognition {\n" +
                "    points: " + toIndentedString(points) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
