/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.greenmark.datafeed.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RevenueBreakdown
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class RevenueBreakdown {
    @SerializedName("symbol")
    private String symbol = null;

    @SerializedName("cik")
    private String cik = null;

    @SerializedName("data")
    private List<BreakdownItem> data = null;

    public RevenueBreakdown symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol
     *
     * @return symbol
     **/
    @Schema(description = "Symbol")
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public RevenueBreakdown cik(String cik) {
        this.cik = cik;
        return this;
    }

    /**
     * CIK
     *
     * @return cik
     **/
    @Schema(description = "CIK")
    public String getCik() {
        return cik;
    }

    public void setCik(String cik) {
        this.cik = cik;
    }

    public RevenueBreakdown data(List<BreakdownItem> data) {
        this.data = data;
        return this;
    }

    public RevenueBreakdown addDataItem(BreakdownItem dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<BreakdownItem>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Array of revenue breakdown over multiple periods.
     *
     * @return data
     **/
    @Schema(description = "Array of revenue breakdown over multiple periods.")
    public List<BreakdownItem> getData() {
        return data;
    }

    public void setData(List<BreakdownItem> data) {
        this.data = data;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RevenueBreakdown revenueBreakdown = (RevenueBreakdown) o;
        return Objects.equals(this.symbol, revenueBreakdown.symbol) &&
                Objects.equals(this.cik, revenueBreakdown.cik) &&
                Objects.equals(this.data, revenueBreakdown.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, cik, data);
    }


    @Override
    public String toString() {

        String sb = "class RevenueBreakdown {\n" +
                "    symbol: " + toIndentedString(symbol) + "\n" +
                "    cik: " + toIndentedString(cik) + "\n" +
                "    data: " + toIndentedString(data) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
