package com.greenmark;

import com.greenmark.core.Stock;
import com.greenmark.database.service.AccountDbService;
import com.greenmark.database.service.StockDbService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.UUID;

@Slf4j
@Component
public class LoadStocks {

    @Autowired
    private StockDbService service;

    public LoadStocks() {
    }

    public boolean load() {

        try {
            service.loadOnStartup(UUID.randomUUID().toString(), "MMM", "3M");
            service.loadOnStartup(UUID.randomUUID().toString(), "AOS", "A. O. Smith");
            service.loadOnStartup(UUID.randomUUID().toString(), "ABT", "Abbott");
            service.loadOnStartup(UUID.randomUUID().toString(), "ABBV", "AbbVie");
            service.loadOnStartup(UUID.randomUUID().toString(), "ACN", "Accenture");
            service.loadOnStartup(UUID.randomUUID().toString(), "ADBE", "Adobe Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "AMD", "Advanced Micro Devices");
            service.loadOnStartup(UUID.randomUUID().toString(), "AES", "AES Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "AFL", "Aflac");
            service.loadOnStartup(UUID.randomUUID().toString(), "A", "Agilent Technologies");
            service.loadOnStartup(UUID.randomUUID().toString(), "APD", "Air Products and Chemicals");
            service.loadOnStartup(UUID.randomUUID().toString(), "ABNB", "Airbnb");
            service.loadOnStartup(UUID.randomUUID().toString(), "AKAM", "Akamai");
            service.loadOnStartup(UUID.randomUUID().toString(), "ALB", "Albemarle Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "ARE", "Alexandria Real Estate Equities");
            service.loadOnStartup(UUID.randomUUID().toString(), "ALGN", "Align Technology");
            service.loadOnStartup(UUID.randomUUID().toString(), "ALLE", "Allegion");
            service.loadOnStartup(UUID.randomUUID().toString(), "LNT", "Alliant Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "ALL", "Allstate");
            service.loadOnStartup(UUID.randomUUID().toString(), "GOOGL", "Alphabet Inc. (Class A)");
            service.loadOnStartup(UUID.randomUUID().toString(), "GOOG", "Alphabet Inc. (Class C)");
            service.loadOnStartup(UUID.randomUUID().toString(), "MO", "Altria");
            service.loadOnStartup(UUID.randomUUID().toString(), "AMZN", "Amazon");
            service.loadOnStartup(UUID.randomUUID().toString(), "AMCR", "Amcor");
            service.loadOnStartup(UUID.randomUUID().toString(), "AEE", "Ameren");
            service.loadOnStartup(UUID.randomUUID().toString(), "AAL", "American Airlines Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "AEP", "American Electric Power");
            service.loadOnStartup(UUID.randomUUID().toString(), "AXP", "American Express");
            service.loadOnStartup(UUID.randomUUID().toString(), "AIG", "American International Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "AMT", "American Tower");
            service.loadOnStartup(UUID.randomUUID().toString(), "AWK", "American Water Works");
            service.loadOnStartup(UUID.randomUUID().toString(), "AMP", "Ameriprise Financial");
            service.loadOnStartup(UUID.randomUUID().toString(), "AME", "Ametek");
            service.loadOnStartup(UUID.randomUUID().toString(), "AMGN", "Amgen");
            service.loadOnStartup(UUID.randomUUID().toString(), "APH", "Amphenol");
            service.loadOnStartup(UUID.randomUUID().toString(), "ADI", "Analog Devices");
            service.loadOnStartup(UUID.randomUUID().toString(), "ANSS", "Ansys");
            service.loadOnStartup(UUID.randomUUID().toString(), "AON", "Aon");
            service.loadOnStartup(UUID.randomUUID().toString(), "APA", "APA Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "AAPL", "Apple Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "AMAT", "Applied Materials");
            service.loadOnStartup(UUID.randomUUID().toString(), "APTV", "Aptiv");
            service.loadOnStartup(UUID.randomUUID().toString(), "ACGL", "Arch Capital Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "ADM", "Archer-Daniels-Midland");
            service.loadOnStartup(UUID.randomUUID().toString(), "ANET", "Arista Networks");
            service.loadOnStartup(UUID.randomUUID().toString(), "AJG", "Arthur J. Gallagher & Co.");
            service.loadOnStartup(UUID.randomUUID().toString(), "AIZ", "Assurant");
            service.loadOnStartup(UUID.randomUUID().toString(), "T", "AT&T");
            service.loadOnStartup(UUID.randomUUID().toString(), "ATO", "Atmos Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "ADSK", "Autodesk");
            service.loadOnStartup(UUID.randomUUID().toString(), "ADP", "Automatic Data Processing");
            service.loadOnStartup(UUID.randomUUID().toString(), "AZO", "AutoZone");
            service.loadOnStartup(UUID.randomUUID().toString(), "AVB", "AvalonBay Communities");
            service.loadOnStartup(UUID.randomUUID().toString(), "AVY", "Avery Dennison");
            service.loadOnStartup(UUID.randomUUID().toString(), "AXON", "Axon Enterprise");
            service.loadOnStartup(UUID.randomUUID().toString(), "BKR", "Baker Hughes");
            service.loadOnStartup(UUID.randomUUID().toString(), "BALL", "Ball Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "BAC", "Bank of America");
            service.loadOnStartup(UUID.randomUUID().toString(), "BK", "Bank of New York Mellon");
            service.loadOnStartup(UUID.randomUUID().toString(), "BBWI", "Bath & Body Works, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "BAX", "Baxter International");
            service.loadOnStartup(UUID.randomUUID().toString(), "BDX", "Becton Dickinson");
            service.loadOnStartup(UUID.randomUUID().toString(), "BRK.B", "Berkshire Hathaway");
            service.loadOnStartup(UUID.randomUUID().toString(), "BBY", "Best Buy");
            service.loadOnStartup(UUID.randomUUID().toString(), "BIO", "Bio-Rad");
            service.loadOnStartup(UUID.randomUUID().toString(), "TECH", "Bio-Techne");
            service.loadOnStartup(UUID.randomUUID().toString(), "BIIB", "Biogen");
            service.loadOnStartup(UUID.randomUUID().toString(), "BLK", "BlackRock");
            service.loadOnStartup(UUID.randomUUID().toString(), "BX", "Blackstone");
            service.loadOnStartup(UUID.randomUUID().toString(), "BA", "Boeing");
            service.loadOnStartup(UUID.randomUUID().toString(), "BKNG", "Booking Holdings");
            service.loadOnStartup(UUID.randomUUID().toString(), "BWA", "BorgWarner");
            service.loadOnStartup(UUID.randomUUID().toString(), "BSX", "Boston Scientific");
            service.loadOnStartup(UUID.randomUUID().toString(), "BMY", "Bristol Myers Squibb");
            service.loadOnStartup(UUID.randomUUID().toString(), "AVGO", "Broadcom Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "BR", "Broadridge Financial Solutions");
            service.loadOnStartup(UUID.randomUUID().toString(), "BRO", "Brown & Brown");
            service.loadOnStartup(UUID.randomUUID().toString(), "BF.B", "Brown–Forman");
            service.loadOnStartup(UUID.randomUUID().toString(), "BLDR", "Builders FirstSource");
            service.loadOnStartup(UUID.randomUUID().toString(), "BG", "Bunge Global SA");
            service.loadOnStartup(UUID.randomUUID().toString(), "BXP", "BXP, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "CDNS", "Cadence Design Systems");
            service.loadOnStartup(UUID.randomUUID().toString(), "CZR", "Caesars Entertainment");
            service.loadOnStartup(UUID.randomUUID().toString(), "CPT", "Camden Property Trust");
            service.loadOnStartup(UUID.randomUUID().toString(), "CPB", "Campbell Soup Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "COF", "Capital One");
            service.loadOnStartup(UUID.randomUUID().toString(), "CAH", "Cardinal Health");
            service.loadOnStartup(UUID.randomUUID().toString(), "KMX", "CarMax");
            service.loadOnStartup(UUID.randomUUID().toString(), "CCL", "Carnival");
            service.loadOnStartup(UUID.randomUUID().toString(), "CARR", "Carrier Global");
            service.loadOnStartup(UUID.randomUUID().toString(), "CTLT", "Catalent");
            service.loadOnStartup(UUID.randomUUID().toString(), "CAT", "Caterpillar Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "CBOE", "Cboe Global Markets");
            service.loadOnStartup(UUID.randomUUID().toString(), "CBRE", "CBRE Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "CDW", "CDW");
            service.loadOnStartup(UUID.randomUUID().toString(), "CE", "Celanese");
            service.loadOnStartup(UUID.randomUUID().toString(), "COR", "Cencora");
            service.loadOnStartup(UUID.randomUUID().toString(), "CNC", "Centene Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "CNP", "CenterPoint Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "CF", "CF Industries");
            service.loadOnStartup(UUID.randomUUID().toString(), "CHRW", "CH Robinson");
            service.loadOnStartup(UUID.randomUUID().toString(), "CRL", "Charles River Laboratories");
            service.loadOnStartup(UUID.randomUUID().toString(), "SCHW", "Charles Schwab Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "CHTR", "Charter Communications");
            service.loadOnStartup(UUID.randomUUID().toString(), "CVX", "Chevron Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "CMG", "Chipotle Mexican Grill");
            service.loadOnStartup(UUID.randomUUID().toString(), "CB", "Chubb Limited");
            service.loadOnStartup(UUID.randomUUID().toString(), "CHD", "Church & Dwight");
            service.loadOnStartup(UUID.randomUUID().toString(), "CI", "Cigna");
            service.loadOnStartup(UUID.randomUUID().toString(), "CINF", "Cincinnati Financial");
            service.loadOnStartup(UUID.randomUUID().toString(), "CTAS", "Cintas");
            service.loadOnStartup(UUID.randomUUID().toString(), "CSCO", "Cisco");
            service.loadOnStartup(UUID.randomUUID().toString(), "C", "Citigroup");
            service.loadOnStartup(UUID.randomUUID().toString(), "CFG", "Citizens Financial Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "CLX", "Clorox");
            service.loadOnStartup(UUID.randomUUID().toString(), "CME", "CME Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "CMS", "CMS Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "KO", "Coca-Cola Company (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "CTSH", "Cognizant");
            service.loadOnStartup(UUID.randomUUID().toString(), "CL", "Colgate-Palmolive");
            service.loadOnStartup(UUID.randomUUID().toString(), "CMCSA", "Comcast");
            service.loadOnStartup(UUID.randomUUID().toString(), "CAG", "Conagra Brands");
            service.loadOnStartup(UUID.randomUUID().toString(), "COP", "ConocoPhillips");
            service.loadOnStartup(UUID.randomUUID().toString(), "ED", "Consolidated Edison");
            service.loadOnStartup(UUID.randomUUID().toString(), "STZ", "Constellation Brands");
            service.loadOnStartup(UUID.randomUUID().toString(), "CEG", "Constellation Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "COO", "Cooper Companies (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "CPRT", "Copart");
            service.loadOnStartup(UUID.randomUUID().toString(), "GLW", "Corning Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "CPAY", "Corpay");
            service.loadOnStartup(UUID.randomUUID().toString(), "CTVA", "Corteva");
            service.loadOnStartup(UUID.randomUUID().toString(), "CSGP", "CoStar Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "COST", "Costco");
            service.loadOnStartup(UUID.randomUUID().toString(), "CTRA", "Coterra");
            service.loadOnStartup(UUID.randomUUID().toString(), "CRWD", "CrowdStrike");
            service.loadOnStartup(UUID.randomUUID().toString(), "CCI", "Crown Castle");
            service.loadOnStartup(UUID.randomUUID().toString(), "CSX", "CSX");
            service.loadOnStartup(UUID.randomUUID().toString(), "CMI", "Cummins");
            service.loadOnStartup(UUID.randomUUID().toString(), "CVS", "CVS Health");
            service.loadOnStartup(UUID.randomUUID().toString(), "DHR", "Danaher Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "DRI", "Darden Restaurants");
            service.loadOnStartup(UUID.randomUUID().toString(), "DVA", "DaVita Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "DAY", "Dayforce");
            service.loadOnStartup(UUID.randomUUID().toString(), "DECK", "Deckers Brands");
            service.loadOnStartup(UUID.randomUUID().toString(), "DE", "Deere & Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "DAL", "Delta Air Lines");
            service.loadOnStartup(UUID.randomUUID().toString(), "DVN", "Devon Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "DXCM", "Dexcom");
            service.loadOnStartup(UUID.randomUUID().toString(), "FANG", "Diamondback Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "DLR", "Digital Realty");
            service.loadOnStartup(UUID.randomUUID().toString(), "DFS", "Discover Financial");
            service.loadOnStartup(UUID.randomUUID().toString(), "DG", "Dollar General");
            service.loadOnStartup(UUID.randomUUID().toString(), "DLTR", "Dollar Tree");
            service.loadOnStartup(UUID.randomUUID().toString(), "D", "Dominion Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "DPZ", "Domino's");
            service.loadOnStartup(UUID.randomUUID().toString(), "DOV", "Dover Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "DOW", "Dow Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "DHI", "DR Horton");
            service.loadOnStartup(UUID.randomUUID().toString(), "DTE", "DTE Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "DUK", "Duke Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "DD", "DuPont");
            service.loadOnStartup(UUID.randomUUID().toString(), "EMN", "Eastman Chemical Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "ETN", "Eaton Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "EBAY", "eBay");
            service.loadOnStartup(UUID.randomUUID().toString(), "ECL", "Ecolab");
            service.loadOnStartup(UUID.randomUUID().toString(), "EIX", "Edison International");
            service.loadOnStartup(UUID.randomUUID().toString(), "EW", "Edwards Lifesciences");
            service.loadOnStartup(UUID.randomUUID().toString(), "EA", "Electronic Arts");
            service.loadOnStartup(UUID.randomUUID().toString(), "ELV", "Elevance Health");
            service.loadOnStartup(UUID.randomUUID().toString(), "EMR", "Emerson Electric");
            service.loadOnStartup(UUID.randomUUID().toString(), "ENPH", "Enphase");
            service.loadOnStartup(UUID.randomUUID().toString(), "ETR", "Entergy");
            service.loadOnStartup(UUID.randomUUID().toString(), "EOG", "EOG Resources");
            service.loadOnStartup(UUID.randomUUID().toString(), "EPAM", "EPAM Systems");
            service.loadOnStartup(UUID.randomUUID().toString(), "EQT", "EQT Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "EFX", "Equifax");
            service.loadOnStartup(UUID.randomUUID().toString(), "EQIX", "Equinix");
            service.loadOnStartup(UUID.randomUUID().toString(), "EQR", "Equity Residential");
            service.loadOnStartup(UUID.randomUUID().toString(), "ESS", "Essex Property Trust");
            service.loadOnStartup(UUID.randomUUID().toString(), "EL", "Estée Lauder Companies (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "ETSY", "Etsy");
            service.loadOnStartup(UUID.randomUUID().toString(), "EG", "Everest Re");
            service.loadOnStartup(UUID.randomUUID().toString(), "EVRG", "Evergy");
            service.loadOnStartup(UUID.randomUUID().toString(), "ES", "Eversource");
            service.loadOnStartup(UUID.randomUUID().toString(), "EXC", "Exelon");
            service.loadOnStartup(UUID.randomUUID().toString(), "EXPE", "Expedia Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "EXPD", "Expeditors International");
            service.loadOnStartup(UUID.randomUUID().toString(), "EXR", "Extra Space Storage");
            service.loadOnStartup(UUID.randomUUID().toString(), "XOM", "ExxonMobil");
            service.loadOnStartup(UUID.randomUUID().toString(), "FFIV", "F5, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "FDS", "FactSet");
            service.loadOnStartup(UUID.randomUUID().toString(), "FICO", "Fair Isaac");
            service.loadOnStartup(UUID.randomUUID().toString(), "FAST", "Fastenal");
            service.loadOnStartup(UUID.randomUUID().toString(), "FRT", "Federal Realty");
            service.loadOnStartup(UUID.randomUUID().toString(), "FDX", "FedEx");
            service.loadOnStartup(UUID.randomUUID().toString(), "FIS", "Fidelity National Information Services");
            service.loadOnStartup(UUID.randomUUID().toString(), "FITB", "Fifth Third Bank");
            service.loadOnStartup(UUID.randomUUID().toString(), "FSLR", "First Solar");
            service.loadOnStartup(UUID.randomUUID().toString(), "FE", "FirstEnergy");
            service.loadOnStartup(UUID.randomUUID().toString(), "FI", "Fiserv");
            service.loadOnStartup(UUID.randomUUID().toString(), "FMC", "FMC Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "F", "Ford Motor Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "FTNT", "Fortinet");
            service.loadOnStartup(UUID.randomUUID().toString(), "FTV", "Fortive");
            service.loadOnStartup(UUID.randomUUID().toString(), "FOXA", "Fox Corporation (Class A)");
            service.loadOnStartup(UUID.randomUUID().toString(), "FOX", "Fox Corporation (Class B)");
            service.loadOnStartup(UUID.randomUUID().toString(), "BEN", "Franklin Templeton");
            service.loadOnStartup(UUID.randomUUID().toString(), "FCX", "Freeport-McMoRan");
            service.loadOnStartup(UUID.randomUUID().toString(), "GRMN", "Garmin");
            service.loadOnStartup(UUID.randomUUID().toString(), "IT", "Gartner");
            service.loadOnStartup(UUID.randomUUID().toString(), "GE", "GE Aerospace");
            service.loadOnStartup(UUID.randomUUID().toString(), "GEHC", "GE HealthCare");
            service.loadOnStartup(UUID.randomUUID().toString(), "GEV", "GE Vernova");
            service.loadOnStartup(UUID.randomUUID().toString(), "GEN", "Gen Digital");
            service.loadOnStartup(UUID.randomUUID().toString(), "GNRC", "Generac");
            service.loadOnStartup(UUID.randomUUID().toString(), "GD", "General Dynamics");
            service.loadOnStartup(UUID.randomUUID().toString(), "GIS", "General Mills");
            service.loadOnStartup(UUID.randomUUID().toString(), "GM", "General Motors");
            service.loadOnStartup(UUID.randomUUID().toString(), "GPC", "Genuine Parts Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "GILD", "Gilead Sciences");
            service.loadOnStartup(UUID.randomUUID().toString(), "GPN", "Global Payments");
            service.loadOnStartup(UUID.randomUUID().toString(), "GL", "Globe Life");
            service.loadOnStartup(UUID.randomUUID().toString(), "GDDY", "GoDaddy");
            service.loadOnStartup(UUID.randomUUID().toString(), "GS", "Goldman Sachs");
            service.loadOnStartup(UUID.randomUUID().toString(), "HAL", "Halliburton");
            service.loadOnStartup(UUID.randomUUID().toString(), "HIG", "Hartford (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "HAS", "Hasbro");
            service.loadOnStartup(UUID.randomUUID().toString(), "HCA", "HCA Healthcare");
            service.loadOnStartup(UUID.randomUUID().toString(), "DOC", "Healthpeak");
            service.loadOnStartup(UUID.randomUUID().toString(), "HSIC", "Henry Schein");
            service.loadOnStartup(UUID.randomUUID().toString(), "HSY", "Hershey's");
            service.loadOnStartup(UUID.randomUUID().toString(), "HES", "Hess Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "HPE", "Hewlett Packard Enterprise");
            service.loadOnStartup(UUID.randomUUID().toString(), "HLT", "Hilton Worldwide");
            service.loadOnStartup(UUID.randomUUID().toString(), "HOLX", "Hologic");
            service.loadOnStartup(UUID.randomUUID().toString(), "HD", "Home Depot (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "HON", "Honeywell");
            service.loadOnStartup(UUID.randomUUID().toString(), "HRL", "Hormel Foods");
            service.loadOnStartup(UUID.randomUUID().toString(), "HST", "Host Hotels & Resorts");
            service.loadOnStartup(UUID.randomUUID().toString(), "HWM", "Howmet Aerospace");
            service.loadOnStartup(UUID.randomUUID().toString(), "HPQ", "HP Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "HUBB", "Hubbell Incorporated");
            service.loadOnStartup(UUID.randomUUID().toString(), "HUM", "Humana");
            service.loadOnStartup(UUID.randomUUID().toString(), "HBAN", "Huntington Bancshares");
            service.loadOnStartup(UUID.randomUUID().toString(), "HII", "Huntington Ingalls Industries");
            service.loadOnStartup(UUID.randomUUID().toString(), "IBM", "IBM");
            service.loadOnStartup(UUID.randomUUID().toString(), "IEX", "IDEX Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "IDXX", "Idexx Laboratories");
            service.loadOnStartup(UUID.randomUUID().toString(), "ITW", "Illinois Tool Works");
            service.loadOnStartup(UUID.randomUUID().toString(), "INCY", "Incyte");
            service.loadOnStartup(UUID.randomUUID().toString(), "IR", "Ingersoll Rand");
            service.loadOnStartup(UUID.randomUUID().toString(), "PODD", "Insulet Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "INTC", "Intel");
            service.loadOnStartup(UUID.randomUUID().toString(), "ICE", "Intercontinental Exchange");
            service.loadOnStartup(UUID.randomUUID().toString(), "IFF", "International Flavors & Fragrances");
            service.loadOnStartup(UUID.randomUUID().toString(), "IP", "International Paper");
            service.loadOnStartup(UUID.randomUUID().toString(), "IPG", "Interpublic Group of Companies (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "INTU", "Intuit");
            service.loadOnStartup(UUID.randomUUID().toString(), "ISRG", "Intuitive Surgical");
            service.loadOnStartup(UUID.randomUUID().toString(), "IVZ", "Invesco");
            service.loadOnStartup(UUID.randomUUID().toString(), "INVH", "Invitation Homes");
            service.loadOnStartup(UUID.randomUUID().toString(), "IQV", "IQVIA");
            service.loadOnStartup(UUID.randomUUID().toString(), "IRM", "Iron Mountain");
            service.loadOnStartup(UUID.randomUUID().toString(), "JBHT", "J.B. Hunt");
            service.loadOnStartup(UUID.randomUUID().toString(), "JBL", "Jabil");
            service.loadOnStartup(UUID.randomUUID().toString(), "JKHY", "Jack Henry & Associates");
            service.loadOnStartup(UUID.randomUUID().toString(), "J", "Jacobs Solutions");
            service.loadOnStartup(UUID.randomUUID().toString(), "JNJ", "Johnson & Johnson");
            service.loadOnStartup(UUID.randomUUID().toString(), "JCI", "Johnson Controls");
            service.loadOnStartup(UUID.randomUUID().toString(), "JPM", "JPMorgan Chase");
            service.loadOnStartup(UUID.randomUUID().toString(), "JNPR", "Juniper Networks");
            service.loadOnStartup(UUID.randomUUID().toString(), "K", "Kellanova");
            service.loadOnStartup(UUID.randomUUID().toString(), "KVUE", "Kenvue");
            service.loadOnStartup(UUID.randomUUID().toString(), "KDP", "Keurig Dr Pepper");
            service.loadOnStartup(UUID.randomUUID().toString(), "KEY", "KeyCorp");
            service.loadOnStartup(UUID.randomUUID().toString(), "KEYS", "Keysight");
            service.loadOnStartup(UUID.randomUUID().toString(), "KMB", "Kimberly-Clark");
            service.loadOnStartup(UUID.randomUUID().toString(), "KIM", "Kimco Realty");
            service.loadOnStartup(UUID.randomUUID().toString(), "KMI", "Kinder Morgan");
            service.loadOnStartup(UUID.randomUUID().toString(), "KKR", "KKR");
            service.loadOnStartup(UUID.randomUUID().toString(), "KLAC", "KLA Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "KHC", "Kraft Heinz");
            service.loadOnStartup(UUID.randomUUID().toString(), "KR", "Kroger");
            service.loadOnStartup(UUID.randomUUID().toString(), "LHX", "L3Harris");
            service.loadOnStartup(UUID.randomUUID().toString(), "LH", "LabCorp");
            service.loadOnStartup(UUID.randomUUID().toString(), "LRCX", "Lam Research");
            service.loadOnStartup(UUID.randomUUID().toString(), "LW", "Lamb Weston");
            service.loadOnStartup(UUID.randomUUID().toString(), "LVS", "Las Vegas Sands");
            service.loadOnStartup(UUID.randomUUID().toString(), "LDOS", "Leidos");
            service.loadOnStartup(UUID.randomUUID().toString(), "LEN", "Lennar");
            service.loadOnStartup(UUID.randomUUID().toString(), "LLY", "Lilly (Eli)");
            service.loadOnStartup(UUID.randomUUID().toString(), "LIN", "Linde plc");
            service.loadOnStartup(UUID.randomUUID().toString(), "LYV", "Live Nation Entertainment");
            service.loadOnStartup(UUID.randomUUID().toString(), "LKQ", "LKQ Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "LMT", "Lockheed Martin");
            service.loadOnStartup(UUID.randomUUID().toString(), "L", "Loews Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "LOW", "Lowe's");
            service.loadOnStartup(UUID.randomUUID().toString(), "LULU", "Lululemon Athletica");
            service.loadOnStartup(UUID.randomUUID().toString(), "LYB", "LyondellBasell");
            service.loadOnStartup(UUID.randomUUID().toString(), "MTB", "M&T Bank");
            service.loadOnStartup(UUID.randomUUID().toString(), "MRO", "Marathon Oil");
            service.loadOnStartup(UUID.randomUUID().toString(), "MPC", "Marathon Petroleum");
            service.loadOnStartup(UUID.randomUUID().toString(), "MKTX", "MarketAxess");
            service.loadOnStartup(UUID.randomUUID().toString(), "MAR", "Marriott International");
            service.loadOnStartup(UUID.randomUUID().toString(), "MMC", "Marsh McLennan");
            service.loadOnStartup(UUID.randomUUID().toString(), "MLM", "Martin Marietta Materials");
            service.loadOnStartup(UUID.randomUUID().toString(), "MAS", "Masco");
            service.loadOnStartup(UUID.randomUUID().toString(), "MA", "Mastercard");
            service.loadOnStartup(UUID.randomUUID().toString(), "MTCH", "Match Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "MKC", "McCormick & Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "MCD", "McDonald's");
            service.loadOnStartup(UUID.randomUUID().toString(), "MCK", "McKesson Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "MDT", "Medtronic");
            service.loadOnStartup(UUID.randomUUID().toString(), "MRK", "Merck & Co.");
            service.loadOnStartup(UUID.randomUUID().toString(), "META", "Meta Platforms");
            service.loadOnStartup(UUID.randomUUID().toString(), "MET", "MetLife");
            service.loadOnStartup(UUID.randomUUID().toString(), "MTD", "Mettler Toledo");
            service.loadOnStartup(UUID.randomUUID().toString(), "MGM", "MGM Resorts");
            service.loadOnStartup(UUID.randomUUID().toString(), "MCHP", "Microchip Technology");
            service.loadOnStartup(UUID.randomUUID().toString(), "MU", "Micron Technology");
            service.loadOnStartup(UUID.randomUUID().toString(), "MSFT", "Microsoft");
            service.loadOnStartup(UUID.randomUUID().toString(), "MAA", "Mid-America Apartment Communities");
            service.loadOnStartup(UUID.randomUUID().toString(), "MRNA", "Moderna");
            service.loadOnStartup(UUID.randomUUID().toString(), "MHK", "Mohawk Industries");
            service.loadOnStartup(UUID.randomUUID().toString(), "MOH", "Molina Healthcare");
            service.loadOnStartup(UUID.randomUUID().toString(), "TAP", "Molson Coors Beverage Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "MDLZ", "Mondelez International");
            service.loadOnStartup(UUID.randomUUID().toString(), "MPWR", "Monolithic Power Systems");
            service.loadOnStartup(UUID.randomUUID().toString(), "MNST", "Monster Beverage");
            service.loadOnStartup(UUID.randomUUID().toString(), "MCO", "Moody's Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "MS", "Morgan Stanley");
            service.loadOnStartup(UUID.randomUUID().toString(), "MOS", "Mosaic Company (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "MSI", "Motorola Solutions");
            service.loadOnStartup(UUID.randomUUID().toString(), "MSCI", "MSCI");
            service.loadOnStartup(UUID.randomUUID().toString(), "NDAQ", "Nasdaq, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "NTAP", "NetApp");
            service.loadOnStartup(UUID.randomUUID().toString(), "NFLX", "Netflix");
            service.loadOnStartup(UUID.randomUUID().toString(), "NEM", "Newmont");
            service.loadOnStartup(UUID.randomUUID().toString(), "NWSA", "News Corp (Class A)");
            service.loadOnStartup(UUID.randomUUID().toString(), "NWS", "News Corp (Class B)");
            service.loadOnStartup(UUID.randomUUID().toString(), "NEE", "NextEra Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "NKE", "Nike, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "NI", "NiSource");
            service.loadOnStartup(UUID.randomUUID().toString(), "NDSN", "Nordson Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "NSC", "Norfolk Southern Railway");
            service.loadOnStartup(UUID.randomUUID().toString(), "NTRS", "Northern Trust");
            service.loadOnStartup(UUID.randomUUID().toString(), "NOC", "Northrop Grumman");
            service.loadOnStartup(UUID.randomUUID().toString(), "NCLH", "Norwegian Cruise Line Holdings");
            service.loadOnStartup(UUID.randomUUID().toString(), "NRG", "NRG Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "NUE", "Nucor");
            service.loadOnStartup(UUID.randomUUID().toString(), "NVDA", "Nvidia");
            service.loadOnStartup(UUID.randomUUID().toString(), "NVR", "NVR, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "NXPI", "NXP Semiconductors");
            service.loadOnStartup(UUID.randomUUID().toString(), "ORLY", "O'Reilly Auto Parts");
            service.loadOnStartup(UUID.randomUUID().toString(), "OXY", "Occidental Petroleum");
            service.loadOnStartup(UUID.randomUUID().toString(), "ODFL", "Old Dominion");
            service.loadOnStartup(UUID.randomUUID().toString(), "OMC", "Omnicom Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "ON", "ON Semiconductor");
            service.loadOnStartup(UUID.randomUUID().toString(), "OKE", "ONEOK");
            service.loadOnStartup(UUID.randomUUID().toString(), "ORCL", "Oracle Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "OTIS", "Otis Worldwide");
            service.loadOnStartup(UUID.randomUUID().toString(), "PCAR", "Paccar");
            service.loadOnStartup(UUID.randomUUID().toString(), "PKG", "Packaging Corporation of America");
            service.loadOnStartup(UUID.randomUUID().toString(), "PANW", "Palo Alto Networks");
            service.loadOnStartup(UUID.randomUUID().toString(), "PARA", "Paramount Global");
            service.loadOnStartup(UUID.randomUUID().toString(), "PH", "Parker Hannifin");
            service.loadOnStartup(UUID.randomUUID().toString(), "PAYX", "Paychex");
            service.loadOnStartup(UUID.randomUUID().toString(), "PAYC", "Paycom");
            service.loadOnStartup(UUID.randomUUID().toString(), "PYPL", "PayPal");
            service.loadOnStartup(UUID.randomUUID().toString(), "PNR", "Pentair");
            service.loadOnStartup(UUID.randomUUID().toString(), "PEP", "PepsiCo");
            service.loadOnStartup(UUID.randomUUID().toString(), "PFE", "Pfizer");
            service.loadOnStartup(UUID.randomUUID().toString(), "PCG", "PG&E Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "PM", "Philip Morris International");
            service.loadOnStartup(UUID.randomUUID().toString(), "PSX", "Phillips 66");
            service.loadOnStartup(UUID.randomUUID().toString(), "PNW", "Pinnacle West");
            service.loadOnStartup(UUID.randomUUID().toString(), "PNC", "PNC Financial Services");
            service.loadOnStartup(UUID.randomUUID().toString(), "POOL", "Pool Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "PPG", "PPG Industries");
            service.loadOnStartup(UUID.randomUUID().toString(), "PPL", "PPL Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "PFG", "Principal Financial Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "PG", "Procter & Gamble");
            service.loadOnStartup(UUID.randomUUID().toString(), "PGR", "Progressive Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "PLD", "Prologis");
            service.loadOnStartup(UUID.randomUUID().toString(), "PRU", "Prudential Financial");
            service.loadOnStartup(UUID.randomUUID().toString(), "PEG", "Public Service Enterprise Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "PTC", "PTC");
            service.loadOnStartup(UUID.randomUUID().toString(), "PSA", "Public Storage");
            service.loadOnStartup(UUID.randomUUID().toString(), "PHM", "PulteGroup");
            service.loadOnStartup(UUID.randomUUID().toString(), "QRVO", "Qorvo");
            service.loadOnStartup(UUID.randomUUID().toString(), "PWR", "Quanta Services");
            service.loadOnStartup(UUID.randomUUID().toString(), "QCOM", "Qualcomm");
            service.loadOnStartup(UUID.randomUUID().toString(), "DGX", "Quest Diagnostics");
            service.loadOnStartup(UUID.randomUUID().toString(), "RL", "Ralph Lauren Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "RJF", "Raymond James");
            service.loadOnStartup(UUID.randomUUID().toString(), "RTX", "RTX Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "O", "Realty Income");
            service.loadOnStartup(UUID.randomUUID().toString(), "REG", "Regency Centers");
            service.loadOnStartup(UUID.randomUUID().toString(), "REGN", "Regeneron");
            service.loadOnStartup(UUID.randomUUID().toString(), "RF", "Regions Financial Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "RSG", "Republic Services");
            service.loadOnStartup(UUID.randomUUID().toString(), "RMD", "ResMed");
            service.loadOnStartup(UUID.randomUUID().toString(), "RVTY", "Revvity");
            service.loadOnStartup(UUID.randomUUID().toString(), "ROK", "Rockwell Automation");
            service.loadOnStartup(UUID.randomUUID().toString(), "ROL", "Rollins, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "ROP", "Roper Technologies");
            service.loadOnStartup(UUID.randomUUID().toString(), "ROST", "Ross Stores");
            service.loadOnStartup(UUID.randomUUID().toString(), "RCL", "Royal Caribbean Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "SPGI", "S&P Global");
            service.loadOnStartup(UUID.randomUUID().toString(), "CRM", "Salesforce");
            service.loadOnStartup(UUID.randomUUID().toString(), "SBAC", "SBA Communications");
            service.loadOnStartup(UUID.randomUUID().toString(), "SLB", "Schlumberger");
            service.loadOnStartup(UUID.randomUUID().toString(), "STX", "Seagate Technology");
            service.loadOnStartup(UUID.randomUUID().toString(), "SRE", "Sempra Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "NOW", "ServiceNow");
            service.loadOnStartup(UUID.randomUUID().toString(), "SHW", "Sherwin-Williams");
            service.loadOnStartup(UUID.randomUUID().toString(), "SPG", "Simon Property Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "SWKS", "Skyworks Solutions");
            service.loadOnStartup(UUID.randomUUID().toString(), "SJM", "J.M. Smucker Company (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "SW", "Smurfit WestRock");
            service.loadOnStartup(UUID.randomUUID().toString(), "SNA", "Snap-on");
            service.loadOnStartup(UUID.randomUUID().toString(), "SOLV", "Solventum");
            service.loadOnStartup(UUID.randomUUID().toString(), "SO", "Southern Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "LUV", "Southwest Airlines");
            service.loadOnStartup(UUID.randomUUID().toString(), "SWK", "Stanley Black & Decker");
            service.loadOnStartup(UUID.randomUUID().toString(), "SBUX", "Starbucks");
            service.loadOnStartup(UUID.randomUUID().toString(), "STT", "State Street Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "STLD", "Steel Dynamics");
            service.loadOnStartup(UUID.randomUUID().toString(), "STE", "Steris");
            service.loadOnStartup(UUID.randomUUID().toString(), "SYK", "Stryker Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "SMCI", "Supermicro");
            service.loadOnStartup(UUID.randomUUID().toString(), "SYF", "Synchrony Financial");
            service.loadOnStartup(UUID.randomUUID().toString(), "SNPS", "Synopsys");
            service.loadOnStartup(UUID.randomUUID().toString(), "SYY", "Sysco");
            service.loadOnStartup(UUID.randomUUID().toString(), "TMUS", "T-Mobile US");
            service.loadOnStartup(UUID.randomUUID().toString(), "TROW", "T. Rowe Price");
            service.loadOnStartup(UUID.randomUUID().toString(), "TTWO", "Take-Two Interactive");
            service.loadOnStartup(UUID.randomUUID().toString(), "TPR", "Tapestry, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "TRGP", "Targa Resources");
            service.loadOnStartup(UUID.randomUUID().toString(), "TGT", "Target Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "TEL", "TE Connectivity");
            service.loadOnStartup(UUID.randomUUID().toString(), "TDY", "Teledyne Technologies");
            service.loadOnStartup(UUID.randomUUID().toString(), "TFX", "Teleflex");
            service.loadOnStartup(UUID.randomUUID().toString(), "TER", "Teradyne");
            service.loadOnStartup(UUID.randomUUID().toString(), "TSLA", "Tesla, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "TXN", "Texas Instruments");
            service.loadOnStartup(UUID.randomUUID().toString(), "TXT", "Textron");
            service.loadOnStartup(UUID.randomUUID().toString(), "TMO", "Thermo Fisher Scientific");
            service.loadOnStartup(UUID.randomUUID().toString(), "TJX", "TJX Companies");
            service.loadOnStartup(UUID.randomUUID().toString(), "TSCO", "Tractor Supply");
            service.loadOnStartup(UUID.randomUUID().toString(), "TT", "Trane Technologies");
            service.loadOnStartup(UUID.randomUUID().toString(), "TDG", "TransDigm Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "TRV", "Travelers Companies (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "TRMB", "Trimble Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "TFC", "Truist");
            service.loadOnStartup(UUID.randomUUID().toString(), "TYL", "Tyler Technologies");
            service.loadOnStartup(UUID.randomUUID().toString(), "TSN", "Tyson Foods");
            service.loadOnStartup(UUID.randomUUID().toString(), "USB", "U.S. Bank");
            service.loadOnStartup(UUID.randomUUID().toString(), "UBER", "Uber");
            service.loadOnStartup(UUID.randomUUID().toString(), "UDR", "UDR, Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "ULTA", "Ulta Beauty");
            service.loadOnStartup(UUID.randomUUID().toString(), "UNP", "Union Pacific Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "UAL", "United Airlines Holdings");
            service.loadOnStartup(UUID.randomUUID().toString(), "UPS", "United Parcel Service");
            service.loadOnStartup(UUID.randomUUID().toString(), "URI", "United Rentals");
            service.loadOnStartup(UUID.randomUUID().toString(), "UNH", "UnitedHealth Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "UHS", "Universal Health Services");
            service.loadOnStartup(UUID.randomUUID().toString(), "VLO", "Valero Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "VTR", "Ventas");
            service.loadOnStartup(UUID.randomUUID().toString(), "VLTO", "Veralto");
            service.loadOnStartup(UUID.randomUUID().toString(), "VRSN", "Verisign");
            service.loadOnStartup(UUID.randomUUID().toString(), "VRSK", "Verisk");
            service.loadOnStartup(UUID.randomUUID().toString(), "VZ", "Verizon");
            service.loadOnStartup(UUID.randomUUID().toString(), "VRTX", "Vertex Pharmaceuticals");
            service.loadOnStartup(UUID.randomUUID().toString(), "VTRS", "Viatris");
            service.loadOnStartup(UUID.randomUUID().toString(), "VICI", "Vici Properties");
            service.loadOnStartup(UUID.randomUUID().toString(), "V", "Visa Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "VST", "Vistra");
            service.loadOnStartup(UUID.randomUUID().toString(), "VMC", "Vulcan Materials Company");
            service.loadOnStartup(UUID.randomUUID().toString(), "WRB", "W. R. Berkley Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "GWW", "W. W. Grainger");
            service.loadOnStartup(UUID.randomUUID().toString(), "WAB", "Wabtec");
            service.loadOnStartup(UUID.randomUUID().toString(), "WBA", "Walgreens Boots Alliance");
            service.loadOnStartup(UUID.randomUUID().toString(), "WMT", "Walmart");
            service.loadOnStartup(UUID.randomUUID().toString(), "DIS", "Walt Disney Company (The)");
            service.loadOnStartup(UUID.randomUUID().toString(), "WBD", "Warner Bros. Discovery");
            service.loadOnStartup(UUID.randomUUID().toString(), "WM", "Waste Management");
            service.loadOnStartup(UUID.randomUUID().toString(), "WAT", "Waters Corporation");
            service.loadOnStartup(UUID.randomUUID().toString(), "WEC", "WEC Energy Group");
            service.loadOnStartup(UUID.randomUUID().toString(), "WFC", "Wells Fargo");
            service.loadOnStartup(UUID.randomUUID().toString(), "WELL", "Welltower");
            service.loadOnStartup(UUID.randomUUID().toString(), "WST", "West Pharmaceutical Services");
            service.loadOnStartup(UUID.randomUUID().toString(), "WDC", "Western Digital");
            service.loadOnStartup(UUID.randomUUID().toString(), "WY", "Weyerhaeuser");
            service.loadOnStartup(UUID.randomUUID().toString(), "WMB", "Williams Companies");
            service.loadOnStartup(UUID.randomUUID().toString(), "WTW", "Willis Towers Watson");
            service.loadOnStartup(UUID.randomUUID().toString(), "WYNN", "Wynn Resorts");
            service.loadOnStartup(UUID.randomUUID().toString(), "XEL", "Xcel Energy");
            service.loadOnStartup(UUID.randomUUID().toString(), "XYL", "Xylem Inc.");
            service.loadOnStartup(UUID.randomUUID().toString(), "YUM", "Yum! Brands");
            service.loadOnStartup(UUID.randomUUID().toString(), "ZBRA", "Zebra Technologies");
            service.loadOnStartup(UUID.randomUUID().toString(), "ZBH", "Zimmer Biomet");
            service.loadOnStartup(UUID.randomUUID().toString(), "ZTS", "Zoetis");
        }
        catch (Exception e) {
            log.error(e.toString());
            return false;
        }
        return true;
    }


}
